
project_id = "ovyakbwetiwkmpqjdhme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.generate-monthly-payments]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = false
