# Configuración compatible con Supabase CLI v1 y superiores
# Ubicación: supabase/config.toml

[auth]
api_external_url = "http://localhost:9999"
site_url = "http://localhost:3000"

[api]
port = 3000

[db]
port = 54322
# Configuración alternativa para search_path (si la anterior no funciona)
initial_sql = "SET search_path TO public, auth, storage;"

[studio]
port = 3001  # Cambiado para evitar conflicto con [api]
enabled = true

[storage]
enabled = true
file_size_limit = "50MB"  # Formato string en vez de número