
export const SUPPORTED_BANK_TRANSFER_COUNTRIES = [
  "Australia",
  "Bangladés",
  "Brasil",
  "Bulgaria",
  "Canadá",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "República Checa",
  "Dinamarca",
  "Egipto",
  "Europa",
  "Georgia",
  "Ghana",
  "Guatemala",
  "Hong Kong",
  "Hungría",
  "India",
  "Indonesia",
  "Israel",
  "Japón",
  "Kenia",
  "Malasia",
  "México",
  "Marruecos",
  "Nepal",
  "Nueva Zelanda",
  "Nigeria",
  "Noruega",
  "Pakistán",
  "Filipinas",
  "Polonia",
  "Rumanía",
  "Singapur",
  "Sudáfrica",
  "Corea del Sur",
  "Sri Lanka",
  "Suecia",
  "Suiza y Liechtenstein",
  "Tanzania",
  "Tailandia",
  "Turquía",
  "Uganda",
  "Ucrania",
  "Emiratos Árabes Unidos",
  "Reino Unido",
  "Estados Unidos de América",
  "Uruguay",
  "Vietnam"
] as const;

