
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment configuration
const ENV = import.meta.env.VITE_APP_ENV || 'development';

// Supabase configuration by environment
const SUPABASE_CONFIG = {
  production: {
    url: "https://ovyakbwetiwkmpqjdhme.supabase.co",
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eWFrYndldGl3a21wcWpkaG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjkzMTksImV4cCI6MjA1NDgwNTMxOX0.2JIEJzWigGcyb46r7iK-H5PIwYK04SzWaKHb7ZZV2bw"
  },
  development: {
    // Replace these with your development Supabase project credentials
    url: import.meta.env.SUPABASE_DEV_URL || "https://icyajoecmxqjgyuhpqaa.supabase.co",
    key: import.meta.env.SUPABASE_DEV_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWFqb2VjbXhxamd5dWhwcWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTkwMjAsImV4cCI6MjA1Njc5NTAyMH0._QpqRVEtP3_eUQTaHTsQVylRO0iTFGbYdrs_89WljP8"
  }
};

// Select configuration based on environment
const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = 
  SUPABASE_CONFIG[ENV === 'production' ? 'production' : 'development'];

console.log(`Using Supabase environment: ${ENV}`);
console.log(`Connecting to Supabase URL: ${SUPABASE_URL}`);
console.log(`Using environment variables: VITE_APP_ENV=${import.meta.env.VITE_APP_ENV || 'not set'}`);
console.log(`Using project ID from config.toml: ${import.meta.env.VITE_SUPABASE_PROJECT_ID || 'not set'}`);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Test connection function - can be called from anywhere to verify connection
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('profiles').select('id').limit(1);
    if (error) {
      console.error('Supabase connection test failed:', error);
      return { success: false, error };
    }
    console.log('Supabase connection successful:', data);
    return { success: true, data };
  } catch (err) {
    console.error('Supabase connection test exception:', err);
    return { success: false, error: err };
  }
};
