// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbxnfzieayzwjursprgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieG5memllYXl6d2p1cnNwcmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDkzODQsImV4cCI6MjA1NjUyNTM4NH0.NbniNSVDvK7etyZFnDTCU2Z133C1_hsGzG7NFaQ84M8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);