name: Release (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push --include-all
      
      # ✅ New step: Deploy all edge functions in supabase/functions/
      - name: Deploy Supabase Edge Functions
        run: |
          for dir in supabase/functions/*/ ; do
            func=$(basename "$dir")
            echo "Deploying function: $func"
            supabase functions deploy "$func"
          done
