name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          echo "PROJECT_ID is: ${SUPABASE_PROJECT_ID:+set}"
          echo "ACCESS_TOKEN is: ${SUPABASE_ACCESS_TOKEN:+set}"
        shell: bash

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push

      # ✅ Fetch develop branch to compare changes
      - name: Fetch develop branch
        run: git fetch origin develop

      # ✅ Deploy only changed Edge Functions
      - name: Deploy Supabase Edge Functions (only if changed)
        run: |
          for dir in supabase/functions/*/ ; do
            func=$(basename "$dir")
            if git diff --quiet origin/develop -- "$dir"; then
              echo "No changes in $func, skipping."
            else
              echo "Deploying function: $func"
              supabase functions deploy "$func"
            fi
          done
