name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          echo "PROJECT_ID is: ${SUPABASE_PROJECT_ID:+set}"
          echo "ACCESS_TOKEN is: ${SUPABASE_ACCESS_TOKEN:+set}"
        shell: bash
        
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
      
      # ✅ New step: Deploy all edge functions in supabase/functions/
      - name: Deploy Supabase Edge Functions
        run: |
          for dir in supabase/functions/*/ ; do
            func=$(basename "$dir")
            echo "Deploying function: $func"
            supabase functions deploy "$func"
          done

